[pytest]
DJANGO_SETTINGS_MODULE = config.django.test
pythonpath = .
testpaths = tests
python_files = test_*.py *_test.py tests.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    --strict-markers
    --strict-config
    --tb=short
    --color=yes
    --code-highlight=yes
    -ra
console_output_style = count
filterwarnings =
    ignore::DeprecationWarning:environ.compat
