# Generated by Django 5.2.5 on 2026-08-19 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='updated at')),
                ('currency', models.CharField(choices=[('USD', 'US dollar'), ('EUR', 'Euro'), ('IRR', 'Iranian rial')], help_text='Currency code for this wallet, such as USD, EUR, or IRR.', max_length=3, verbose_name='Currency')),
                ('balance', models.BigIntegerField(default=0, help_text='Current wallet balance in whole units of the selected currency.', verbose_name='Balance')),
                ('user', models.ForeignKey(help_text='Owner of this wallet.', on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
                'constraints': [models.UniqueConstraint(fields=('user', 'currency'), name='unique_wallet_user_currency'), models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_non_negative')],
            },
        ),
    ]
