# Generated by Django 5.1.1 on 2026-08-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="remaining_limit",
            field=models.BigIntegerField(
                default=0,
                help_text="Remaining transferable amount for the current limitation period.",
                verbose_name="Remaining limit",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                condition=models.Q(("remaining_limit__gte", 0)),
                name="wallet_remaining_limit_non_negative",
            ),
        ),
    ]
