# Generated by Django 5.2.5 on 2026-08-19 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLedger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated.', verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this transaction.', primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField(help_text='Client-supplied key that guarantees at-most-once processing.', unique=True, verbose_name='Idempotency key')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer')], help_text='Kind of wallet movement: deposit, withdrawal, or transfer.', max_length=20, verbose_name='Transaction type')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Processing status of this transaction.', max_length=20, verbose_name='Status')),
                ('amount', models.BigIntegerField(help_text='Transaction amount in whole units of the wallet currency.', verbose_name='Amount')),
                ('currency', models.CharField(choices=[('USD', 'US dollar'), ('EUR', 'Euro'), ('IRR', 'Iranian rial')], help_text='Currency code for this transaction.', max_length=3, verbose_name='Currency')),
                ('description', models.TextField(blank=True, default=None, help_text='Optional note describing this transaction.', null=True, verbose_name='Description')),
                ('receiver_wallet', models.ForeignKey(blank=True, help_text='Wallet credited for deposits and transfers.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to='wallets.wallet', verbose_name='Receiver wallet')),
                ('sender_wallet', models.ForeignKey(blank=True, help_text='Wallet debited for withdrawals and transfers.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='wallets.wallet', verbose_name='Sender wallet')),
            ],
            options={
                'verbose_name': 'transaction ledger entry',
                'verbose_name_plural': 'transaction ledger entries',
                'indexes': [models.Index(fields=['status'], name='transaction_status_7a6f4f_idx'), models.Index(fields=['sender_wallet', 'created_at'], name='tx_sender_created_idx'), models.Index(fields=['receiver_wallet', 'created_at'], name='tx_receiver_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive')],
            },
        ),
    ]
