from config.settings.i18n import TIME_ZONE
from config.settings.rabbitmq import RABBITMQ_BROKER_URL

CELERY_BROKER_URL = RABBITMQ_BROKER_URL
CELERY_RESULT_BACKEND = "django-db"
CELERY_RESULT_EXTENDED = True
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
