# Generated by Django 5.2.5 on 2026-08-19 12:36

import ledger.accounts.validators.iranian_phone_number
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Iranian mobile phone number (11 digits starting with 09).', max_length=11, unique=True, validators=[ledger.accounts.validators.iranian_phone_number.validate_iranian_phone_number], verbose_name='Phone number'),
        ),
    ]
